kind: ServiceAccount
apiVersion: v1
metadata:
  name: release-csi-zadara-controller-sa
  namespace: kube-system
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: zadara-csi
    app.kubernetes.io/instance: release
    app.kubernetes.io/version: "1.3.2"
    app: zadara-csi
    version: 1.3.2
    release: release
    stage: "production"
    publisher: "zadara"
    provisioner: csi.zadara.com
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-csi-zadara-provisioner-role
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: zadara-csi
    app.kubernetes.io/instance: release
    app.kubernetes.io/version: "1.3.2"
    app: zadara-csi
    version: 1.3.2
    release: release
    stage: "production"
    publisher: "zadara"
    provisioner: csi.zadara.com
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["get", "list"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch"]
---
# Attacher must be able to work with PVs, nodes and VolumeAttachments
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-csi-zadara-attacher-role
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: zadara-csi
    app.kubernetes.io/instance: release
    app.kubernetes.io/version: "1.3.2"
    app: zadara-csi
    version: 1.3.2
    release: release
    stage: "production"
    publisher: "zadara"
    provisioner: csi.zadara.com
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs: ["patch"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-csi-zadara-snapshotter-role
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: zadara-csi
    app.kubernetes.io/instance: release
    app.kubernetes.io/version: "1.3.2"
    app: zadara-csi
    version: 1.3.2
    release: release
    stage: "production"
    publisher: "zadara"
    provisioner: csi.zadara.com
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents/status"]
    verbs: ["update"]
---
# Resizer must be able to work with PVCs, PVs, SCs.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-csi-zadara-resizer
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: zadara-csi
    app.kubernetes.io/instance: release
    app.kubernetes.io/version: "1.3.2"
    app: zadara-csi
    version: 1.3.2
    release: release
    stage: "production"
    publisher: "zadara"
    provisioner: csi.zadara.com
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"]
    verbs: ["patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-csi-zadara-provisioner-binding
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: zadara-csi
    app.kubernetes.io/instance: release
    app.kubernetes.io/version: "1.3.2"
    app: zadara-csi
    version: 1.3.2
    release: release
    stage: "production"
    publisher: "zadara"
    provisioner: csi.zadara.com
subjects:
  - kind: ServiceAccount
    name: release-csi-zadara-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: release-csi-zadara-provisioner-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-csi-zadara-attacher-binding
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: zadara-csi
    app.kubernetes.io/instance: release
    app.kubernetes.io/version: "1.3.2"
    app: zadara-csi
    version: 1.3.2
    release: release
    stage: "production"
    publisher: "zadara"
    provisioner: csi.zadara.com
subjects:
  - kind: ServiceAccount
    name: release-csi-zadara-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: release-csi-zadara-attacher-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-csi-zadara-snapshotter-binding
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: zadara-csi
    app.kubernetes.io/instance: release
    app.kubernetes.io/version: "1.3.2"
    app: zadara-csi
    version: 1.3.2
    release: release
    stage: "production"
    publisher: "zadara"
    provisioner: csi.zadara.com
subjects:
  - kind: ServiceAccount
    name: release-csi-zadara-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: release-csi-zadara-snapshotter-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-csi-resizer-role
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: zadara-csi
    app.kubernetes.io/instance: release
    app.kubernetes.io/version: "1.3.2"
    app: zadara-csi
    version: 1.3.2
    release: release
    stage: "production"
    publisher: "zadara"
    provisioner: csi.zadara.com
subjects:
  - kind: ServiceAccount
    name: release-csi-zadara-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: release-csi-zadara-resizer
  apiGroup: rbac.authorization.k8s.io
---
# Sidecars must be able to work with endpoints in current namespace
# if (and only if) leadership election is enabled
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kube-system
  name: release-csi-zadara-leader-election-role
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-csi-zadara-leader-election-binding
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: release-csi-zadara-controller-sa
    namespace: kube-system
roleRef:
  kind: Role
  name: release-csi-zadara-leader-election-role
  apiGroup: rbac.authorization.k8s.io
---
