kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: release-csi-zadara-node
  namespace: kube-system
  labels:
    app.kubernetes.io/component: node
    app.kubernetes.io/name: zadara-csi
    app.kubernetes.io/instance: release
    app.kubernetes.io/version: "1.3.2"
    app: zadara-csi
    version: 1.3.2
    release: release
    stage: "production"
    publisher: "zadara"
    provisioner: csi.zadara.com
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: node
      app.kubernetes.io/name: zadara-csi
      app.kubernetes.io/instance: release
      app.kubernetes.io/version: "1.3.2"
      app: zadara-csi
      version: "1.3.2"
      release: release
      stage: "production"
      publisher: "zadara"
      provisioner: csi.zadara.com
  template:
    metadata:
      labels:
        app.kubernetes.io/component: node
        app.kubernetes.io/name: zadara-csi
        app.kubernetes.io/instance: release
        app.kubernetes.io/version: "1.3.2"
        app: zadara-csi
        version: 1.3.2
        release: release
        stage: "production"
        publisher: "zadara"
        provisioner: csi.zadara.com
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: release-csi-zadara-node-sa
      hostNetwork: true
      containers:
        #######################################################################
        - name: csi-node-driver-registrar
          image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0
          imagePullPolicy: "IfNotPresent"
          args:
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/csi.zadara.com/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        #######################################################################
        - name: liveness-probe
          image: k8s.gcr.io/sig-storage/livenessprobe:v2.3.0
          imagePullPolicy: "IfNotPresent"
          args:
            - "--csi-address=/csi/csi.sock"
            - "--health-port=9808"
            - "--probe-timeout=3s"
            - "--v=5"
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        #######################################################################
        - name: csi-zadara-driver
          image: "zadara/csi-driver:1.3.2"
          imagePullPolicy: "IfNotPresent"
          args:
            - "zadara-csi"
            - "--hostname=example.zadaravpsa.com"
            - "--use-tls=true"
            - "--verify-tls=true"
            - "--name=csi.zadara.com"
            - "--endpoint=unix:///csi/csi.sock"
          env:
            - name: VPSA_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: release-vpsa-access-token
                  key: access-token
            - name: ISCSIADM_MODE
              value: "client-server"
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 5
          ports:
            - name: healthz
              containerPort: 9808
              protocol: TCP
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: iscsi-socket
              mountPath: /iscsi-socket/iscsi.sock
            - name: iscsi-initiator-name
              mountPath: /etc/iscsi/initiatorname.iscsi
            - name: socket-dir
              mountPath: /csi
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet
              # needed so that any mounts setup inside this container are
              # propagated back to the host machine.
              mountPropagation: "Bidirectional"
            - name: device-dir
              mountPath: /dev
            - name: config-dir
              mountPath: /etc/csi
      volumes:
        - name: iscsi-socket
          hostPath:
            path: /var/zadara/csi-iscsi.sock
            type: FileOrCreate
        - name: iscsi-initiator-name
          hostPath:
            path: /etc/iscsi/initiatorname.iscsi
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: DirectoryOrCreate
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi.zadara.com
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
        - name: config-dir
          configMap:
            name: release-csi-config-map
---
