---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-io-test-0-snapshot-clone
spec:
  storageClassName: io-test-sc
  dataSource:
    name: nas-io-test-0-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
