apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zadara-csi-vsc
  ## annotations store arbitrary metadata.
  ## Uncomment example below to set StorageClass as default.
  # annotations:
  #  storageclass.kubernetes.io/is-default-class: "true"
## provisioner refers to CSI driver name as appears in 'kubectl get csidrivers'
provisioner: csi.zadara.com
## reclaimPolicy tells the cluster what to do with the PersistentVolume and VPSA Volume,
## when PVC is deleted. Allowed values: "Delete" or "Retain".
reclaimPolicy: Delete
## allowVolumeExpansion allows you to edit or patch an existing PVC and increase its capacity.
allowVolumeExpansion: true
## parameters are driver-specific settings, see examples below
parameters: {}
  # VSCStorageClass: vscstorageclass-sample
  # volumeOptions: '{"nfsanonuid":"65500", "nfsanongid":"65500"}'
