---
# The snapshot controller implements the control loop for CSI snapshot functionality.
# It should be installed as part of the base Kubernetes distribution in an appropriate
# namespace for components implementing base system functionality. For installing with
# Vanilla Kubernetes, kube-system makes sense for the namespace.
kind: Deployment
apiVersion: apps/v1
metadata:
  # name is intentionally not templated: there should only be one snapshot-controller
  name: snapshot-controller
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.snapshotController.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: snapshot-controller
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: snapshot-controller
        {{- include "helm.labels" . | nindent 8 }}
    spec:
      serviceAccountName: snapshot-controller-sa
      containers:
        - name: snapshot-controller
          image: "{{ .Values.snapshotController.image }}"
          args:
            - "--leader-election"
            - "--v=5"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
