---
# VSC custom resources
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-vsc
  labels:
    app.kubernetes.io/component: controller
    {{- include "helm.labels" . | nindent 4 }}
rules:
  - apiGroups: ["storage.zadara.com"]
    resources: ["*"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: [ "get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-vsc-role
  labels:
    app.kubernetes.io/component: controller
    {{- include "helm.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-controller-sa
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-vsc
  apiGroup: rbac.authorization.k8s.io
