---
{{- if .Values.customTrustedCertificates }}
{{- if .Values.customTrustedCertificates.plainText }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-custom-tls-cert
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
stringData:
  {{ .Release.Name }}-tls.crt: |-
    {{- .Values.customTrustedCertificates.plainText | nindent 4 }}
{{- end }}
{{- end }}
