kind: Deployment
apiVersion: apps/v1
metadata:
  name: release-csi-zadara-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: zadara-csi
    app.kubernetes.io/instance: release
    app.kubernetes.io/version: "1.3.2"
    app: zadara-csi
    version: 1.3.2
    release: release
    stage: "production"
    publisher: "zadara"
    provisioner: csi.zadara.com
spec:
  replicas: 1  # TODO expose
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: zadara-csi
      app.kubernetes.io/instance: release
      app.kubernetes.io/version: "1.3.2"
      app: zadara-csi
      version: "1.3.2"
      release: release
      stage: "production"
      publisher: "zadara"
      provisioner: csi.zadara.com
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: zadara-csi
        app.kubernetes.io/instance: release
        app.kubernetes.io/version: "1.3.2"
        app: zadara-csi
        version: 1.3.2
        release: release
        stage: "production"
        publisher: "zadara"
        provisioner: csi.zadara.com
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: release-csi-zadara-controller-sa
      containers:
        #######################################################################
        - name: csi-provisioner
          image: k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
          imagePullPolicy: "IfNotPresent"
          args:
            - "--csi-address=$(ADDRESS)"
            - "--leader-election"
            - "--timeout=180s"
            - "--http-endpoint=:8080"
            - "--extra-create-metadata"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /healthz/leader-election
              port: http-endpoint
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 20
          ports:
            - containerPort: 8080
              name: http-endpoint
              protocol: TCP
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        #######################################################################
        - name: csi-attacher
          image: k8s.gcr.io/sig-storage/csi-attacher:v3.2.1
          imagePullPolicy: "IfNotPresent"
          args:
            - "--csi-address=$(ADDRESS)"
            - "--leader-election"
            - "--timeout=180s"
            - "--http-endpoint=:8081"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /healthz/leader-election
              port: http-endpoint
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 20
          ports:
            - containerPort: 8081
              name: http-endpoint
              protocol: TCP
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        #######################################################################
        - name: csi-snapshotter
          imagePullPolicy: "IfNotPresent"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          
          image: k8s.gcr.io/sig-storage/csi-snapshotter:v4.1.1
          args:
            - "--csi-address=$(ADDRESS)"
            - "--leader-election"
            - "--timeout=180s"
            - "--http-endpoint=:8082"
            - "--v=5"
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /healthz/leader-election
              port: http-endpoint
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 20
          ports:
            - containerPort: 8082
              name: http-endpoint
              protocol: TCP
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        #######################################################################
        - name: csi-resizer
          image: k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
          imagePullPolicy: "IfNotPresent"
          args:
            - "--csi-address=$(ADDRESS)"
            - "--leader-election"
            - "--timeout=15s"
            - "--http-endpoint=:8083"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /healthz/leader-election
              port: http-endpoint
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 20
          ports:
            - containerPort: 8083
              name: http-endpoint
              protocol: TCP
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        #######################################################################
        - name: liveness-probe
          image: k8s.gcr.io/sig-storage/livenessprobe:v2.3.0
          imagePullPolicy: "IfNotPresent"
          args:
            - "--csi-address=/csi/csi.sock"
            - "--health-port=9808"
            - "--probe-timeout=3s"
            - "--v=5"
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        #######################################################################
        - name: csi-zadara-driver
          image: "zadara/csi-driver:1.3.2"
          imagePullPolicy: "IfNotPresent"
          args:
            - "zadara-csi"
            - "--hostname=example.zadaravpsa.com"
            - "--use-tls=true"
            - "--verify-tls=true"
            - "--name=csi.zadara.com"
            - "--endpoint=unix:///csi/csi.sock"
            - "--controller=true"
          env:
            - name: VPSA_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: release-vpsa-access-token
                  key: access-token
            - name: ISCSIADM_MODE
              value: "rootfs"
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 5
          ports:
            - name: healthz
              containerPort: 9808
              protocol: TCP
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: config-dir
              mountPath: /etc/csi
      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: config-dir
          configMap:
            name: release-csi-config-map
---
