---
# Register driver at cluster-level
# https://kubernetes-csi.github.io/docs/csi-driver-object.html
#
# Usage:
#  kubectl create -f csi-driver.yaml

apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: "{{ .Values.plugin.provisioner }}"
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  attachRequired: true
  podInfoOnMount: true
