---
{{- if .Values.plugin.autoExpandSupport }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-csi-zadara-expander-sa
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: expander
    {{- include "helm.labels" . | nindent 4 }}
{{ end -}}
---
{{- if .Values.plugin.autoExpandSupport }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-csi-zadara-expander
  labels:
    app.kubernetes.io/component: expander
    {{- include "helm.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "update"]
{{ end -}}
---
{{- if .Values.plugin.autoExpandSupport }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-csi-expander-role
  labels:
    app.kubernetes.io/component: expander
    {{- include "helm.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-csi-zadara-expander-sa
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-csi-zadara-expander
  apiGroup: rbac.authorization.k8s.io
{{ end -}}
