---
# Instructions:
# 1. Get access-token from VPSA, and paste here
# 2. Execute "kubectl create -f secrets.yaml", where secrets.yaml is this file
# 3. To verify: "kubectl -n {{ .Values.namespace }} get secrets", vpsa-access-token should appear
# 4. Remove this file, to keep your secrets safe
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-vpsa-access-token
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
stringData:
  access-token: "{{ .Values.vpsa.token }}"
---
{{- if .Values.customTrustedCertificates }}
{{- if .Values.customTrustedCertificates.plainText }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-custom-tls-cert
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
stringData:
  {{ .Release.Name }}-tls.crt: |-
    {{- .Values.customTrustedCertificates.plainText | nindent 4 }}
{{- end }}
{{- end }}
