---
{{ if .Values.plugin.stonith.enable }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-stonith-sa
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: stonith
    {{- include "helm.labels" . | nindent 4 }}
{{- end }}
---
{{ if .Values.plugin.stonith.enable }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-stonith-role
  labels:
    app.kubernetes.io/component: stonith
    {{- include "helm.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "delete"]
{{- end }}
---
{{ if .Values.plugin.stonith.enable }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-stonith-binding
  labels:
    app.kubernetes.io/component: stonith
    {{- include "helm.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-stonith-sa
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-stonith-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
