apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: release-csi-config-map
  labels:
    app.kubernetes.io/name: zadara-csi
    app.kubernetes.io/instance: release
    app.kubernetes.io/version: "1.3.1"
    app: zadara-csi
    version: 1.3.1
    release: release
    stage: "production"
    publisher: "zadara"
    provisioner: csi.zadara.com
data:
  zadara-csi-config.yaml: |-
    vpsa:
      # VPSA Requests timeout in seconds. See http://vpsa-api.zadarastorage.com/#timeouts
      requestTimeoutSec: 180
    plugin:
      # Volume size [GiB] used when no storage specified in PersistentVolumeClaim
      defaultVolumeSizeGiB: 100
    logLevel:
      # Verbosity level for logs. Allowed values: panic, fatal, error, warn or warning, info, debug
      general: "info"
      csi: "info"
    # Use colored output in logs. Does not auto-detect pipes, redirection, or other non-interactive outputs.
    useLogColors: "true"
---
