---
# Register driver at cluster-level
# https://kubernetes-csi.github.io/docs/csi-driver-object.html
#
# Usage:
#  kubectl create -f csi-driver.yaml
#
# Requires K8s 1.14+
apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: "csi.zadara.com"
  labels:
    app.kubernetes.io/name: zadara-csi
    app.kubernetes.io/instance: release
    app.kubernetes.io/version: "1.2.0"
    app: zadara-csi
    version: 1.2.0
    release: release
    stage: "production"
    publisher: "zadara"
    provisioner: csi.zadara.com
spec:
  attachRequired: true
  podInfoOnMount: true
