#############################################
## StorageClass
#############################################
{{- if .Values.nas }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Release.Name }}-nas
provisioner: {{ .Values.storageClass.provisioner }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
allowVolumeExpansion: true
{{ if .Values.storageClass.poolid }}
parameters:
  poolid: {{ .Values.storageClass.poolid }}
{{ end -}}
---
{{ end -}}
{{- if .Values.block }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Release.Name }}-block
provisioner: {{ .Values.storageClass.provisioner }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
allowVolumeExpansion: true
{{ if .Values.storageClass.poolid }}
parameters:
  poolid: {{ .Values.storageClass.poolid }}
{{ end -}}
---
{{ end -}}
#############################################
## PersistentVolumeClaim
#############################################
{{- if .Values.nas}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Values.nas.name }}
spec:
  accessModes:
    - {{ .Values.nas.accessMode }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.nas.capacity }}
  storageClassName: {{ .Release.Name }}-nas
---
{{ end -}}
{{- if .Values.block }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Values.block.name }}
spec:
  accessModes:
    - {{ .Values.block.accessMode }}
  volumeMode: Block
  resources:
    requests:
      storage: {{ .Values.block.capacity }}
  storageClassName: {{ .Release.Name }}-block
---
{{ end -}}
#############################################
## Pod
#############################################
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-{{ .Values.pod.name }}
spec:
  containers:
    - name: {{ .Values.pod.container.name }}
      image: {{ .Values.pod.image }}
      {{- if .Values.pod.args }}
      args:
        {{- range .Values.pod.args }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- if .Values.pod.env }}
      env:
        {{- range .Values.pod.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
      {{- end }}
      {{- if .Values.nas }}
      volumeMounts:
        - name: my-nas
          mountPath: {{ .Values.nas.mountPath }}
      {{- end }}
      {{- if .Values.block }}
      volumeDevices:
        - name: my-block
          devicePath: {{ .Values.block.devicePath }}
      securityContext:
        capabilities:
          add: ["SYS_ADMIN"]
      {{- end }}
  volumes:
    {{- if .Values.nas }}
    - name: my-nas
      persistentVolumeClaim:
        claimName: {{ .Release.Name }}-{{ .Values.nas.name }}
        readOnly: {{ .Values.nas.readOnly }}
    {{- end -}}
    {{- if .Values.block }}
    - name: my-block
      persistentVolumeClaim:
        claimName: {{ .Release.Name }}-{{ .Values.block.name }}
        readOnly: {{ .Values.block.readOnly }}
    {{- end -}}
