{{- if .Values.cleanup.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-pvc-deleter-role
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "delete", "deletecollection"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-pvc-deleter-sa
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-pvc-deleter-rolebinding
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-pvc-deleter-role
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-pvc-deleter-sa
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-pvc-deleter-job
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      activeDeadlineSeconds: 120
      restartPolicy: OnFailure
      containers:
      - name: {{ .Release.Name }}-post-delete-job
        image: {{ .Values.cleanup.image }}
        command: ["kubectl"]
        args:
        - "delete"
        - "pvc"
        - "--selector=app={{ .Release.Name }}"
      serviceAccountName: {{ .Release.Name }}-pvc-deleter-sa
{{ end -}}
