---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Release.Name }}-sc
provisioner: {{ .Values.storageClass.provisioner }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
allowVolumeExpansion: true
mountOptions:
  {{- range .Values.storageClass.mountOptions }}
  - {{ . | quote }}
  {{- end }}
parameters:
  {{- range $key, $val := .Values.storageClass.parameters }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
