apiVersion: v1
entries:
  one-pod-one-pool:
  - apiVersion: v2
    created: "2021-07-14T08:50:08.962480326-04:00"
    description: Example deployment using Zadara-CSI NAS & Block volumes, with one-pool
      VPSA
    digest: d147bb423511ce620ddeedd00642365cd08a64e5b633ee047a2749ec54415144
    name: one-pod-one-pool
    urls:
    - one-pod-one-pool-0.1.0.tgz
    version: 0.1.0
  snapshots-v1:
  - apiVersion: v2
    appVersion: 4.1.1
    created: "2021-07-14T08:50:08.963245469-04:00"
    description: Common infrastructure for v1 CSI Snapshots. Includes snapshots CRDs,
      cluster-global Snapshot Controller, and RBAC for it.
    digest: a41fd499205c51af0075a17c62248ebf933526f2d79b5a127dd3b8b030c455fe
    kubeVersion: '>= 1.20.0'
    name: snapshots-v1
    type: application
    urls:
    - snapshots-v1-4.1.1+zadara.1.tgz
    version: 4.1.1+zadara.1
  snapshots-v1beta1:
  - apiVersion: v2
    appVersion: 3.3.0
    created: "2021-07-14T08:50:08.963926656-04:00"
    description: Common infrastructure for v1beta1 CSI Snapshots. Includes snapshots
      CRDs, cluster-global Snapshot Controller, and RBAC for it.
    digest: 6f888fc6a4774125a45bba585c79451b735caa5fbeae3346a98ddee6676a207e
    kubeVersion: '>= 1.17.0'
    name: snapshots-v1beta1
    type: application
    urls:
    - snapshots-v1beta1-3.3.0+zadara.1.tgz
    version: 3.3.0+zadara.1
  zadara-csi:
  - apiVersion: v1
    appVersion: 1.3.5
    created: "2021-07-14T08:50:08.96556662-04:00"
    description: Container Storage Interface (CSI) driver for Zadara VPSA
    digest: d21afff3be40932c888008eb57829f14bfe45df63bfd1181e25cf6bd101679cd
    home: https://github.com/zadarastorage/zadara-csi
    icon: https://raw.githubusercontent.com/zadarastorage/zadara-csi/release-v0.14.0/helm/zadara-csi/icon.png
    keywords:
    - CSI
    - Storage
    - Zadara
    - VPSA
    - NAS
    - Block
    - Persistent Volume
    - Cloud Storage
    - STaaS
    - PVC
    kubeVersion: '>= 1.18.0'
    maintainers:
    - email: k8s@zadara.com
      name: Zadara Kubernetes team
      url: https://support.zadarastorage.com/
    name: zadara-csi
    urls:
    - zadara-csi-2.2.0.tgz
    version: 2.2.0
generated: "2021-07-14T08:50:08.961627549-04:00"
