apiVersion: v1
entries:
  one-pod-one-pool:
  - apiVersion: v2
    created: "2021-07-18T10:00:53.679325081-04:00"
    description: Example deployment using Zadara-CSI NAS & Block volumes, with one-pool
      VPSA
    digest: 27746799b5737c9866a069363a7c18c96d5f76126fa2b5525e8d546ed8e7557c
    name: one-pod-one-pool
    urls:
    - one-pod-one-pool-0.1.0.tgz
    version: 0.1.0
  snapshots-v1:
  - apiVersion: v2
    appVersion: 4.1.1
    created: "2021-07-18T10:00:53.680200859-04:00"
    description: Common infrastructure for v1 CSI Snapshots. Includes snapshots CRDs,
      cluster-global Snapshot Controller, and RBAC for it.
    digest: 2bde2f4980e424721ff405d9a12b5fe7ae8c5e934810a1f98f8a1469f4fdc5c9
    kubeVersion: '>= 1.20.0'
    name: snapshots-v1
    type: application
    urls:
    - snapshots-v1-4.1.1+zadara.1.tgz
    version: 4.1.1+zadara.1
  snapshots-v1beta1:
  - apiVersion: v2
    appVersion: 3.3.0
    created: "2021-07-18T10:00:53.680982707-04:00"
    description: Common infrastructure for v1beta1 CSI Snapshots. Includes snapshots
      CRDs, cluster-global Snapshot Controller, and RBAC for it.
    digest: 2607ebddd25be83103fbafed643c6732e1d369348c3ff9e19fc45d69a66a66cb
    kubeVersion: '>= 1.17.0'
    name: snapshots-v1beta1
    type: application
    urls:
    - snapshots-v1beta1-3.3.0+zadara.1.tgz
    version: 3.3.0+zadara.1
  zadara-csi:
  - apiVersion: v1
    appVersion: 1.3.6
    created: "2021-07-18T10:00:53.682764121-04:00"
    description: Container Storage Interface (CSI) driver for Zadara VPSA
    digest: 80c28ba3dde6ea32c7b3dab728dbd7a01ec968a4e0808195382e0ec170781e8f
    home: https://github.com/zadarastorage/zadara-csi
    icon: https://raw.githubusercontent.com/zadarastorage/zadara-csi/release-v0.14.0/helm/zadara-csi/icon.png
    keywords:
    - CSI
    - Storage
    - Zadara
    - VPSA
    - NAS
    - Block
    - Persistent Volume
    - Cloud Storage
    - STaaS
    - PVC
    kubeVersion: '>= 1.18.0'
    maintainers:
    - email: k8s@zadara.com
      name: Zadara Kubernetes team
      url: https://support.zadarastorage.com/
    name: zadara-csi
    urls:
    - zadara-csi-2.2.1.tgz
    version: 2.2.1
generated: "2021-07-18T10:00:53.678429074-04:00"
