apiVersion: v1
entries:
  one-pod-one-pool:
  - apiVersion: v2
    created: "2021-11-21T05:01:19.305259702-05:00"
    description: Example deployment using Zadara-CSI NAS & Block volumes, with one-pool
      VPSA
    digest: 9af30ccc41600a7dbc3cbde0bdbb75d64242a3b313157143fb7ff344a2ec767b
    name: one-pod-one-pool
    urls:
    - one-pod-one-pool-0.1.0.tgz
    version: 0.1.0
  snapshots-v1:
  - apiVersion: v2
    appVersion: 4.1.1
    created: "2021-11-21T05:01:19.306116911-05:00"
    description: Common infrastructure for v1 CSI Snapshots. Includes snapshots CRDs,
      cluster-global Snapshot Controller, and RBAC for it.
    digest: a7079e545b4f13c003575678dc45262ddab9049b0cc780db3de986af4d93c9c5
    kubeVersion: '>= 1.20.0'
    name: snapshots-v1
    type: application
    urls:
    - snapshots-v1-4.1.1+zadara.1.tgz
    version: 4.1.1+zadara.1
  snapshots-v1beta1:
  - apiVersion: v2
    appVersion: 3.3.0
    created: "2021-11-21T05:01:19.306947854-05:00"
    description: Common infrastructure for v1beta1 CSI Snapshots. Includes snapshots
      CRDs, cluster-global Snapshot Controller, and RBAC for it.
    digest: d822bce3ce2925a2135c6c1586c61afe0b4ef28817e8fdffa66f8e5bb6e328b9
    kubeVersion: '>= 1.17.0'
    name: snapshots-v1beta1
    type: application
    urls:
    - snapshots-v1beta1-3.3.0+zadara.1.tgz
    version: 3.3.0+zadara.1
  zadara-csi:
  - apiVersion: v1
    appVersion: 1.3.9
    created: "2021-11-21T05:01:19.309587114-05:00"
    description: Container Storage Interface (CSI) driver for Zadara VPSA
    digest: edc080e14e4e9387b100a80fe396dd8e460b0306d2de141353ff1d7819314893
    home: https://github.com/zadarastorage/zadara-csi
    icon: https://raw.githubusercontent.com/zadarastorage/zadara-csi/release-v0.14.0/helm/zadara-csi/icon.png
    keywords:
    - CSI
    - Storage
    - Zadara
    - VPSA
    - NAS
    - Block
    - Persistent Volume
    - Cloud Storage
    - STaaS
    - PVC
    kubeVersion: '>= 1.18.0'
    maintainers:
    - email: k8s@zadara.com
      name: Zadara Kubernetes team
      url: https://support.zadarastorage.com/
    name: zadara-csi
    urls:
    - zadara-csi-2.3.2.tgz
    version: 2.3.2
generated: "2021-11-21T05:01:19.304372196-05:00"
