---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-from-snapshot
spec:
  storageClassName: io-test-nas
  dataSource:
    name: nas-snapshot-test
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
